sudo: required

services:
  - docker

language: python

install:
  - pip install cookiecutter
  - pip install codacy-coverage
  - chmod +x ./test.sh

script:
  - ./test.sh
  - ls -lRa .
  - python-codacy-coverage -r target/project_name/coverage.xml
